### ISSUE TITLE
INSTALLING.md have wrong instructions

### ISSUE THREAD

**Issue by felipevolpone** [dropbox/pyston#1000]
Hey guys, the file INSTALLING.md, in the section "Building and testing" has broken links to clone the clang and llvm. I send a PR ( #999 ) to fix it.

**Comment by kmod** [comment]
Interesting, it works for me (and our buildbots).  What sort of issue are you running into?

I think using an ssh-based clone will only work if you have a github account and have the corresponding ssh key loaded, so I'd prefer to stay away from that.  If there's some sort of an issue, maybe we could switch to `https://`?

**Comment by felipevolpone** [comment]
I'm getting this error:
![captura de tela 2015-11-08 as 16 55 29](https://cloud.githubusercontent.com/assets/1590527/11021982/fe48a9f4-8639-11e5-8d3d-d4c301f5f1e1.png)

Anyway, I think that change it to https it's a better solution. Also, I fixed it in the PR.

**Comment by undingen** [comment]
Works for me too. Maybe you have a firewall in between which blocks the git protocol which AFAIK uses port 9418?
Does ```telnet github.com 9418``` work for you?

**Comment by kmod** [comment]
Yeah sounds like a firewall issue, but I guess we might as well support that.  I'm trying to get the tests to pass (seeing some weirdness with travis-ci -- it said the tests ran for 8 minutes but failed because they took longer than 20 minutes); I know it's a doc-only change but I wanted the tests to pass on principle :)

**Comment by felipevolpone** [comment]
It's a firewall/proxy issue, I'm trying to do this in the network of my university. The tests are stable now?

**Comment by kmod** [comment]
Closed by #999
