### ISSUE TITLE
Unexpected 'callType not defined for int' error

### ISSUE THREAD

**Issue by mpwassell** [dropbox/pyston#1046]
The following code gives this error:
```python
def fn():
    a=1
    if callable(a):
        a()

for i in range(10000):
    fn()
```
If function versioning is re-enabled then for similar reasons code in Django will give a similar error:
django/db/models/sql/query.py, line 1088.
django/utils/tree.py. line 24

**Comment by undingen** [comment]
Thanks for the nice testcase. I will take a look
