### ISSUE TITLE
Should PyObject_GetItem allow an unhandled exception?

### ISSUE THREAD

**Issue by Daetalus** [dropbox/pyston#1161]
In CPython, we can set an exception, but not handle it immediately, then call `PyObject_GetItem` . But in Pyston, if there has an exception that not handled yet out there, `PyObject_GetItem` will report an error.

For example, here are the minimum snippets:

**Test module**
```cpp
#include <Python.h>

static PyObject*
test(PyObject* self, PyObject* args)
{
    PyErr_Format(PyExc_ValueError, "Throw an error before PyObject_GetItem");

    PyObject* a_dict;
    PyObject* index = PyInt_FromLong(0);
    PyObject_GetItem(a_dict, index);

    return NULL;
}

static PyMethodDef TestMethods[] = {
    {"test", test, METH_VARARGS, NULL},
    {NULL, NULL, 0, NULL}
};

PyMODINIT_FUNC
initnumpy_test(void)
{
    (void) Py_InitModule("numpy_test", TestMethods);
}
```

**setup.py**
```python
from distutils.core import setup, Extension

module1 = Extension('numpy_test', sources = ['test_module.c'])

setup (name = 'PackageName',
        version = '1.0',
        description = 'Test the behaviour of CPython and NumPy',
        ext_modules = [module1])
```

In CPython, it will throw that exception normally. But in Pyston, the `PyObject_GetItem` will abort if there has an existed error.

More speficially, in Pyston, the calling chain is here:
https://github.com/dropbox/pyston/blob/refcounting/src/runtime/objmodel.cpp#L4976
https://github.com/dropbox/pyston/blob/refcounting/src/runtime/objmodel.cpp#L6304

I found this problem when try to build an `ndtype` through a dict, NumPy set an exception first(line 1082), and call `PyObject_GetItem` later(line 1098):
https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/descriptor.c#L1077
https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/descriptor.c#L1098

My proposal is use `goto fail` in https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/descriptor.c#L1082 directly. But I afraid other 3rd patry libs will use this "feature" too. So the other solution is make some change in Pyston side, for example, throw an exception in `PyObject_GetItem` before do actually work.

@nathanielherman @kmod @undingen What's your suggestion?

**Comment by kmod** [comment]
PyDict_GetItem is special when it comes to exception handling -- it never throws any exceptions, and it's careful to save+restore the original exception.  So I think this is a little bit different from the normal "what should we do about calling into the C API with an exception set" since it seems fairly clear that we need to support it in this case.

I think the problem with our implementation is that we added a fast-path and forgot/didn't add the exception save+restore to the fast path.  (We have a fast path because our PyDict_GetItem supports more than just dicts, to support attrwrappers.)  So I think we could either add the save+restore to the fast path, or move the fast path inside the save+restore.

**Comment by kmod** [comment]
Did we end up addressing this?  Seems like something we should fix.

**Comment by Daetalus** [comment]
Some notes: this problem was fixed. Maybe one of @undingen 's  exception related fixing fixed it. But we don't know which one did it. Leave this message here just in case anyone wonder why I closed this issue.

**Comment by kmod** [comment]
Oh shoot, I misread your original comment as being about PyDict_GetItem, which is special.  I ran into this PyObject_GetItem issue today, and I addressed it by loosening the PyErr_Occurred() checks if we have imported a third party extension module.  (I'll push that soon.)
