### ISSUE TITLE
Fix evaluation order for dict operations

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#1191]
See [literals_order.py](https://github.com/dropbox/pyston/blob/master/test/tests/literals_order.py)

For dictionaries literals like `{a:b, c:d}`, we first evaluate all of the subexpressions, and then assemble the dict.  We should switch to CPython's order, which is incrementally adding the key-value pairs to the dict as we evaluate them.

**Comment by sizeoftank** [comment]
The test literals_order.py has been removed ?
File blob/refcounting/test/tests/literals_order.py not found

**Comment by Daetalus** [comment]
No, just the `refcounting` branch was removed. Please see the file in `master` branch. https://github.com/dropbox/pyston/blob/master/test/tests/literals_order.py

**Comment by undingen** [comment]
I updated the link in the original comment from kmod to point to master

**Comment by sizeoftank** [comment]
It looks like in create the temporary variable in ` remapDict() ` , I try to set ` wrap_with_assign = false ` and it runs the correct order. 
But a strange thing happened when I running  ` make check_literals_order `, It outputs this differ:
```
Traceback (most recent call last):
  File "./tools/tester.py", line 456, in worker_thread
  File "./tools/tester.py", line 172, in run_test
  File "./tools/tester.py", line 359, in determine_test_result
Exception: Failed on /home/chenwei/pyston/test/tests/literals_order.py:
--- /tmp/expected_FDg4Bo	2016-07-16 06:15:35.835442174 +0800
+++ /tmp/received__NL8z3	2016-07-16 06:15:35.835442174 +0800
@@ -5,15 +5,15 @@
 hashing 1L
 hashing 2
 hashing 1
 eq
 testing dicts
-Creating 4
 Creating 1
+Creating 4
 hashing 1
-Creating 5
 Creating 2
+Creating 5
 hashing 2
-Creating 6
 Creating 1L
+Creating 6
 hashing 1L
 eq
```

**Comment by sizeoftank** [comment]
Oh I forgot to update IR compiler in previous.
