### ISSUE TITLE
add type.__basicsize__, type.__itemsize__,..

### ISSUE THREAD

**Issue by undingen** [dropbox/pyston#1216]
we miss this and other members of `type`.
I think we can copy the implementation from cpython. 
This should be easy starter project and may let `test/cpython/test_types.py` pass

**Comment by sizeoftank** [comment]
In pyston implementation, I see that the ` tp_basicsize ` and ` tp_itemsize ` attributes are already assigned by BoxedClass's constuctor. 
So if only to give ` type_cls ` the attribute member `__basicsize__` and ` __itemsize__ `  could fix this issue?

**Comment by kmod** [comment]
Yep!  It looks like we have the underlying C attributes (tp_basicsize and tp_itemsize) but we need to expose them to Python by adding the `__basicsize__` and `__itemsize__` members to type_cls.

**Comment by sizeoftank** [comment]
Create this PR: #1276
