### ISSUE TITLE
Pyston didn't defined PY_LLONG_MAX yet.

### ISSUE THREAD

**Issue by Daetalus** [dropbox/pyston#1242]
CPython 2.7.7 defined `PY_LLONG_MAX` and other macro in `Include/pyport.h`. But Pyston missed it. Cython rely on it:

https://github.com/Daetalus/cython/commit/9d0fff29d26f6d9aa2f251a3402db4e0b9c6a0b3#diff-b68ea089583bb1818ad9a4fb39c5d534R232

I see no harm to introduce it. Maybe it just Pyston based on an old version of CPython?

**Comment by undingen** [comment]
I think we started with an empty `pyport.h` a long time ago and than one by one copied in stuff we needed when starting to add CAPI support. I think now it's time to just copy over the whole file and add the few pyston additions to it.
