### ISSUE TITLE
Incompatibility of PyCFunction_GET_FUNCTION

### ISSUE THREAD

**Issue by Daetalus** [dropbox/pyston#1260]
Cython will call `PyCFunction_GET_FUNCTION` in here.
https://github.com/Daetalus/cython/blob/master/Cython/Utility/ObjectHandling.c#L1392

In CPython, it doesn't do type check:
```
#define PyCFunction_GET_FUNCTION(func) \
(((PyCFunctionObject *)func) -> m_ml -> ml_meth)
```

But Pyston changed it to function call:
```
#define PyCFunction_GET_FUNCTION(func) \
        PyCFunction_GetFunction((PyObject*)(func))
```

in that function, it will check the type exactly, so it does not work for cases when `op` is not exactly of `PyCFunction_Type` but inherits from this type. It will return `NULL`, and get segfault in here:
https://github.com/Daetalus/cython/blob/master/Cython/Utility/ObjectHandling.c#L1397

What about re-enable those macros?

**Comment by undingen** [comment]
As a first step my suggestions would be to just allow subclasses inside our getter functions. Maybe this way this can still help to catch errors until we are sure everything works?

**Comment by Daetalus** [comment]
Close it due to the first commit in https://github.com/dropbox/pyston/pull/1267 fixed it.
