### ISSUE TITLE
"setitem"  broken invariants in jitted code.

### ISSUE THREAD

**Issue by Daetalus** [dropbox/pyston#1269]
In `setitem` https://github.com/dropbox/pyston/blob/master/src/runtime/objmodel.cpp#L6476 : 
```
extern "C" void setitem(Box* target, Box* slice, Box* value) {
    // ... 
    if (m && m->mp_ass_subscript && m->mp_ass_subscript != slot_mp_ass_subscript) {
        if (rewriter.get()) {
            RewriterVar* r_obj = rewriter->getArg(0);
            RewriterVar* r_slice = rewriter->getArg(1);
            RewriterVar* r_value = rewriter->getArg(2);
            RewriterVar* r_cls = r_obj->getAttr(offsetof(Box, cls));
            RewriterVar* r_m = r_cls->getAttr(offsetof(BoxedClass, tp_as_mapping));
            r_m->addGuardNotEq(0);
            rewriter->call(true, (void*)setitemHelper, r_obj, r_slice, r_value);
            rewriter->commit();
        }

        setitemHelper(target, slice, value);
        return;
    }
```

The jitted code will broken invariants. 

The `target->cls->tp_as_mapping->mp_ass_subscript` is `NULL` when run under `rewriter.get()` in https://github.com/dropbox/pyston/blob/master/src/runtime/objmodel.cpp#L6455. If comment out the code in `rewriter.get()`. The segfault was gone.

For technical reasons, currently I can't provide a minimun snippet. Sorry, but I will try it.

**Comment by undingen** [comment]
can you check if this fixes the crash:
```
RewriterVar* r_m = r_cls->getAttr(offsetof(BoxedClass, tp_as_mapping));
r_m->addGuardNotEq(0);
r_m->addAttrGuard(offsetof(PyMappingMethods, mp_ass_subscript), (intptr_t)m->mp_ass_subscript);
// or
// r_m->addAttrGuard(offsetof(PyMappingMethods, mp_ass_subscript), (intptr_t)0, true);
```

**Comment by undingen** [comment]
or my preferred version :smile: :
```c++
    if (m && m->mp_ass_subscript && m->mp_ass_subscript != slot_mp_ass_subscript) {
        if (rewriter.get()) {
            RewriterVar* r_obj = rewriter->getArg(0);
            RewriterVar* r_slice = rewriter->getArg(1);
            RewriterVar* r_value = rewriter->getArg(2);
            RewriterVar* r_cls = r_obj->getAttr(offsetof(Box, cls));
            RewriterVar* r_m = r_cls->getAttr(offsetof(BoxedClass, tp_as_mapping));
            r_m->addGuardNotEq(0);
            r_m->addAttrGuard(offsetof(PyMappingMethods, mp_ass_subscript), (intptr_t)m->mp_ass_subscript);
            RewriterVar* r_ret = rewriter->call(true, (void*)m->mp_ass_subscript, r_obj, r_slice, r_value);
            rewriter->checkAndThrowCAPIException(r_ret, -1, assembler::MovType::L);
            rewriter->commit();
        }

        int ret = m->mp_ass_subscript(target, slice, value);
        if (ret == -1)
            throwCAPIException();
        return;
    }
```
thanks :+1:

**Comment by Daetalus** [comment]
Thanks, that's could work!

**Comment by undingen** [comment]
`r_m->addAttrGuard` emits code which will load the 64bit value at the offset `offsetof(PyMappingMethods, mp_ass_subscript)` from `r_m` and compares it with the value `m->mp_ass_subscript` (which is a constant value).
basically doing something like this for a 64bit immediate
```
val = m->mp_ass_subscript

mov val, tmp_reg
cmp r_m[offsetof(PyMappingMethods, mp_ass_subscript)], tmp_reg
jne next_slot
```

We could leave this `setitemHelper`  but we do it in other areas in our code base without such a helper and I find the code without the helper slightly easier to understand. And without using the helper we transform one indirect call location to a constant call which theoretically should be slightly faster. (In the future we could do a approach in between and not embed a the destination address but instead do an indirect call (but without the helper).

you can try to write a simple example which triggers this rewrite path and look at the output using the perf_jit.py or annotate.py tool (or gdb) to better understand what the code does.

**Comment by Daetalus** [comment]
Fixed by https://github.com/dropbox/pyston/pull/1280.
