### ISSUE TITLE
Support dummy members in BoxedCode?

### ISSUE THREAD

**Issue by Daetalus** [dropbox/pyston#1285]
Cython will trigger `PyCode_New` assert in here:
https://github.com/dropbox/pyston/blob/master/src/runtime/code.cpp#L140

```
extern "C" PyCodeObject* PyCode_New(int argcount, int nlocals, int stacksize, int flags, PyObject* code,
                                    PyObject* consts, PyObject* names, PyObject* varnames, PyObject* freevars,
                                    PyObject* cellvars, PyObject* filename, PyObject* name, int firstlineno,
                                    PyObject* lnotab) noexcept {
    // Check if this is a dummy code object like PyCode_NewEmpty generates.
    // Because we currently support dummy ones only.
    bool is_dummy = argcount == 0 && nlocals == 0 && stacksize == 0 && flags == 0;
    is_dummy = is_dummy && code == EmptyString && lnotab == EmptyString;
    for (auto&& var : { consts, names, varnames, freevars, cellvars })
        is_dummy = is_dummy && var == EmptyTuple;
    RELEASE_ASSERT(is_dummy, "not implemented");
    // ok this is an empty/dummy code object
```

SciPy need to call this function with empty bytecode but only have file attributes, probably for tracebacks.
https://github.com/cython/cython/commit/36780b2a

My idea is add some `PyCodeObject` members to `BoxedCode`. Just leave these as a "place holders". And remove the release assert. But trigger assert if the `code` parameter truelly contains something. Thoughts?

**Comment by kmod** [comment]
I think it depends on which of the fields it is trying to set -- in general this seems to be a scary thing, but it could definitely be the case that the assert is being more aggressive than it needs to be.

Trying to parse what that cython code is doing, it looks like it will try to set argcount, nlocals, and varnames -- and I think we can actually allow that, because we don't do anything with those or support getting them back out.

**Comment by Daetalus** [comment]
In Pyston, `argcount` and `varnames` was get from `FunctionMetadata`, if Cython set it by calling `PyCode_New`. In this case, the `BoxedCode->f` is `NULL`. So just abandon those two members? And what about `nlocals`?
