### ISSUE TITLE
Change build system?

### ISSUE THREAD

**Issue by darnuria** [dropbox/pyston#13]
Have you plan to move to an other build system like Cmake or ~~autotools~~?
This will be in your roadmap #11 ?

Thanks! And sorry to disturb you but this questions seems important.

**Comment by darnuria** [comment]
Hello I viewed this issue still opened in my dashboard. It seems that this #460 PR resolved this bug.
So I think this is time to close it two years later!

A good bug is a resolved and closed bug. :)

**Comment by kmod** [comment]
Can't believe we (by which I mean @dagar) made it happen!
