### ISSUE TITLE
Using EXIT_SUCCESS and EXIT_FAILURE

### ISSUE THREAD

**Issue by corona10** [dropbox/pyston#1368]
I read [article](https://accu.org/index.php/journals/1706) by Matthew Wilson. and it could be adopt in our project.
In `jit.cpp` we are using constant such as 0, 1, 2 for `rtncode`.
How about using `EXIT_SUCCESS` and `EXIT_FAILURE` for `jit.cpp`

**Comment by kmod** [comment]
I would normally agree, but in this case I think I lean more towards "doing it however CPython does it", which for-better-or-worse is hardcoding 0/1/2.  I think it would be great to bring this up with the CPython developers though to change it upstream :)

**Comment by corona10** [comment]
Okay thanks.
