### ISSUE TITLE
Any chance of a blog update ?

### ISSUE THREAD

**Issue by stuaxo** [dropbox/pyston#1372]
It's been over a year since https://blog.pyston.org/ it would be great to have an update on performance and compatibility etc.

Other stuff that might be interesting 
- Has anyone got this working on new platforms (Windows / Raspberry Pi) ?
- Anyone worked on any python3 support ?

**Comment by kmod** [comment]
I think we might be looking at the dates differently -- we did a blog post about two months ago.  But regardless, you are right that we should post more :)

We have some pretty cool memory savings coming down the pipe, and some more useful-but-not-sexy compatibility fixes.  Maybe we will release an 0.5.2 soon and do a blog post to showcase them :)

But still no concrete plans to work on Windows / python3 support.

**Comment by stuaxo** [comment]
Doh, definitely had one open one that said 2015... but yes, current one is much more recent - so much for github issue just before sleep.

Memory savings are always great :)
