### ISSUE TITLE
missing include/longintrepr.h

### ISSUE THREAD

**Issue by Samureus** [dropbox/pyston#1376]
Hi, not sure if it's important, I was just browsing the include folder and it's missing longintrepr.h. I can confirm that it's included in CPython 2.7.7, both the one downloaded from python.org https://www.python.org/ftp/python/2.7.7/Python-2.7.7.tar.xz and in:

https://github.com/python/cpython/blob/2.7/Include/longintrepr.h

**Comment by Daetalus** [comment]
I'm no sure I understand your situation. But Pyston's long implementation is based on GMP, not implemented from scratch like CPython. So most of the definitions in this file are meanless to Pyston. In general, this file should not be included, unless you compile NumPy `mtrand.c` which generated by unpatched Cython 0.24(Maybe you need to use Pyston patched Cython 0.24, 0.25a0 is still testing.)

**Comment by Samureus** [comment]
Thanks for the tip, I think I know what was missing, I'll test something later.

**Comment by Samureus** [comment]
Closing this issue, thinking on a workaround. Thanks!
