### ISSUE TITLE
[Question] GIL

### ISSUE THREAD

**Issue by redradist** [dropbox/pyston#1429]
Hi guys,

In your blog you have mentioned that you have experimental GIL remove ?
```
We have an experimental configuration option to use a read-write-lock variant, which “removes the GIL” and allows multiple threads to use multiple cores, but the potential parallelism is highly limited by the semantics of the C API.
```

Is it real ? What flag should I pass to compile `pyston` to get this functionality ?

**Comment by kmod** [comment]
The no-gil version is long dead, it was removed here: https://github.com/dropbox/pyston/commit/fe5fc7
It wouldn't have worked once we switched to reference counting anyway.
