### ISSUE TITLE
Implement finalizers

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#158]
These are quite difficult in Python due to the possibility of object resurrection, ie a __del__ method is allowed to store a reference to 'self' somewhere, stopping the deallocation of the object.

I think PyPy has an smart and/or efficient implementation for this: http://doc.pypy.org/en/release-2.0-beta2/discussion/finalizer-order.html

**Comment by rudi-c** [comment]
This can be closed now :)

**Comment by kmod** [comment]
nice :)
