### ISSUE TITLE
Collect + intern our usage of static strings in the runtime

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#163]
There are a large number of places that we refer to strings such as "__call__" or "__init__", etc.  We end up either turning the string constant into a std::string for every call, or we have multiple static std::strings for the same string value.  We should probably just collect all of them into a single place and change all uses to reference those; we've started to do that [here](https://github.com/dropbox/pyston/blob/master/src/runtime/objmodel.cpp#L58), but the job isn't finished.

**Comment by rudi-c** [comment]
With all the internStringImmortal(s), this is done right?
