### ISSUE TITLE
Set GMP to use our GC as its allocator

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#167]
Currently GMP (the bignum library we use) uses malloc()/free() to manage bignum memory.  This means that 1) we never free bignum memory, and 2) we don't get nice behavior if we run out of memory [well that's not something we support well anyway].

GMP supports custom allocators, and it looks like we should be able to just set it to use our GC:
https://gmplib.org/manual/Custom-Allocation.html
example of another project that did it:
http://git.savannah.gnu.org/cgit/guile.git/commit/?id=b57bf2724a254cf73e255b3d2bca0a7dcad6674a

**Comment by dorafmon** [comment]
Hi, I am trying to fix this issue and this is how I do it:
In long.cpp I define:
```
void * customised_allocation(size_t alloc_size){
    return gc::gc_alloc(alloc_size, gc::GCKind::CONSERVATIVE);
}

void * customised_realloc(void *ptr, size_t old_size, size_t new_size){
    return gc::gc_realloc(ptr, new_size);
}

void customised_free(void *ptr, size_t size){
    gc::gc_free(ptr);
}

```

and then in ``setupLong()`` I have this at the beginning:
```
    mp_set_memory_functions(
        customised_allocation,
        customised_realloc,
        customised_free);
```

But I kept getting error saying the free is fed with a pointer that it don't know what to do with. Is there any thing wrong I did that seems obvious for you? Thanks.

**Comment by dorafmon** [comment]
Never mind I fixed the bug.
