### ISSUE TITLE
Start running CPython's tests

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#179]
While it's nice that we have our own tests, we might as well start running some of the CPython tests too.

Not sure what we can do immediately, since most of the tests would probably need to be whittled down a little bit in order to work (ex taking out pickling-testing, etc).

**Comment by dagar** [comment]
Tried running cpython/Lib/test/regrtest.py
Asserts at import json, shutil, unittest

**Comment by kmod** [comment]
We don't support running things through regrtest.py (I think it doesn't guard against exceptions during imports), but we're running the CPython tests so I'm going to close this.
