### ISSUE TITLE
Report "thread_memory_model_test.py" FAILED (Timed out) sometimes

### ISSUE THREAD

**Issue by zhuangh** [dropbox/pyston#180]
I compiled the pyston, and use "make check -j 4", sometimes (many times), test/tests/thread_memory_model_test.py FAILED (Timed out). Sometimes, it passed. 

I use "make run_thread_memory_model_test" to see, sometime, it hangs there, consumes longer runtime, then finish. 

1. When pass:
856us finishing up
./pyston_dbg ../test/tests/thread_memory_model_test.py  0.68s user 0.05s system 94% cpu 0.778 total

2. When Failed 
818us finishing up
./pyston_dbg ../test/tests/thread_memory_model_test.py  5.08s user 0.07s system 100% cpu 5.114 total

**Comment by kmod** [comment]
I improved GIL fairness a couple weeks ago and I haven't seen this issue since then, so I'm going to mark it resolved for now.

**Comment by zhuangh** [comment]
thanks
