### ISSUE TITLE
Support "import _collections"

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#192]
This is the C extension module that implements some of the collections module.  To test it, you can run
`make EXTRA_STDMODULE_SRCS=_collectionsmodule.c"

It looks like the set of things to do is pretty small:
- Py_BEGIN_ALLOW_THREADS / Py_END_ALLOW_THREADS (just need to be defined to be function calls to our "releaseGLWrite" and "acquireGLWrite" functions)
- Do the same object-size hack for PyDictObject that we do for PyStringObject and PyTypeObject
- Add PyEval_CallObject (just a trampoline to our code)

**Comment by kmod** [comment]
All in all that's actually not too much stuff to be done!  If you're interested in getting it working, I would look up where PY_FORMAT_SIZE_T is defined in CPython and add it to our appropriate header file.

PyDictObject is tricky since it's implemented using a C++ std::unordered_map, which we can't reference from C code.  What we've been doing so far is just create a struct that has the right size, but instead of using the unordered_map, add a char[] buffer with the appropriate size (56 in the libstdc++ we're using).  We should add a build step that measures this for us so it's not hardcoded, but for now it's what we're doing in other places and it will get things working.

**Comment by aisk** [comment]
OK, I'll try myself, thank you~
