### ISSUE TITLE
``make check`` bug?

### ISSUE THREAD

**Issue by dorafmon** [dropbox/pyston#251]
Hi, I was trying to run the test for pyston by running ``make check`` and I have the following error:

> *** stack smashing detected ***: /home/bobfang/pyston/pyston_dbg terminated
                      ./test/tests/callattr.py    Correct output (256.2ms)
*** stack smashing detected ***: python terminated
./test/tests/capi_slots.py:
Traceback (most recent call last):
  File "./tools/tester.py", line 333, in worker_thread
    results[job[0]] = run_test(*job)
  File "./tools/tester.py", line 198, in run_test
    expected_code, expected_out, expected_err = get_expected_output(fn)
  File "./tools/tester.py", line 94, in get_expected_output
    assert code >= 0, "CPython exited with an unexpected exit code: %d" % (code,)
AssertionError: CPython exited with an unexpected exit code: -6
Makefile:856: recipe for target 'check_dbg' failed
make[1]: *** [check_dbg] Error 1
make[1]: Leaving directory '/home/bobfang/pyston'
Makefile:389: recipe for target 'check' failed
make: *** [check] Error 2

I have checked using python to run ``capi_slots.py`` and it turns out that python don't now how to import slots_test. How can I fix this? Thanks.

**Comment by kmod** [comment]
Can you post the output of `ls ~/pyston/test/test_extension/build`?  We currently hardcode the path to the extension modules, so if your system used a different directory name it won't be able to find them.

**Comment by dorafmon** [comment]
Hi the output is:

     lib.linux-x86_64-2.7  temp.linux-x86_64-2.7

**Comment by kmod** [comment]
Hmm ok, can you try
```
make ext_python
PYTHONPATH=test/test_extension/build/lib.linux-x86_64-2.7 python test/tests/capi_slots.py
```
(The tester adds that PYTHONPATH variable, so if you run a test by hand without adding it you'll get import errors.)

**Comment by dorafmon** [comment]
After I run the command the test still crashes, the make ext_python succeeded.

    *** stack smashing detected ***: python terminated
    [1]    13302 abort (core dumped)  PYTHONPATH=test/test_extension/build/lib.linux-x86_64-2.7 python

**Comment by kmod** [comment]
Ok sounds like this is involved (some sort of issue with our tester extension module) -- let's try following up on gitter?

**Comment by kmod** [comment]
Fixed in https://github.com/dropbox/pyston/commit/88b6a093294f3b24991a73f0a221d44450976739
