### ISSUE TITLE
Error when compiling gc_unittest

### ISSUE THREAD

**Issue by dorafmon** [dropbox/pyston#252]
Hi, I am trying to compile ``gc_unittest``  and I got the following error:

> pyston: Linking gc_unittest
/home/bobfang/pyston_deps/gtest-1.7.0/src/gtest-all.o:gtest-all.cc:function std::vector<testing::TestPartResult, std::allocator<testing::TestPartResult> >::_M_range_check(unsigned long) const: error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
/home/bobfang/pyston_deps/gtest-1.7.0/src/gtest-all.o:gtest-all.cc:function std::vector<testing::TestProperty, std::allocator<testing::TestProperty> >::_M_range_check(unsigned long) const: error: undefined reference to 'std::__throw_out_of_range_fmt(char const*, ...)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:358: recipe for target 'gc_unittest' failed
make: *** [gc_unittest] Error 1

I tried to update my glibc but it does not seem to work, do you have any idea why this happens?

**Comment by kmod** [comment]
Hmm I'm guessing it's because the install instructions build gtest with the system libstdc++ headers, and then link it with the freshly-built libstdc++.  I don't know why this hasn't caused issues before.

Can you try running this:
```shell
cd ~/pyston_deps/gtest-1.7.0
make distclean
./configure CXXFLAGS="-fno-omit-frame-pointer -isystem $HOME/pyston_deps/gcc-4.8.2-install/include/c++/4.8.2"
make

cd ~/pyston
make gc_unittest
```

If that works I'll update the directions.

**Comment by dorafmon** [comment]
Hi, it worked! :smile:
