### ISSUE TITLE
Finish old-style-class support

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#254]
We need to delegate the new-style special attributes (set on the class "instance") to the old-style ones (set on instances of the "classobj" class).  Each individual one isn't too hard but we just need to go through and add them and make sure they are tested.  Here's what one looks like, from codegen/classobj.cpp:

```c++
Box* instanceGetitem(Box* _inst, Box* key) {
    RELEASE_ASSERT(_inst->cls == instance_cls, "");
    BoxedInstance* inst = static_cast<BoxedInstance*>(_inst);

    Box* getitem_func = _instanceGetattribute(inst, boxStrConstant("__getitem__"), true);
    return runtimeCall(getitem_func, ArgPassSpec(1), key, NULL, NULL, NULL, NULL);
}

void setupClassobj() {
    [...]
    instance_cls->giveAttr("__getitem__", new BoxedFunction(boxRTFunction((void*)instanceGetitem, UNKNOWN, 2)));
    [...]
}
```

This could probably also be made generic, since it's all boilerplate except for the name of the attribute and the number of arguments.

Browsing https://docs.python.org/2/reference/datamodel.html it looks like we don't support the following dunder methods:
- [ ] lt/le/eq/ne/gt/ge
- [ ] cmp/rcmp
- [x] hash
- [x] setattr, delattr
- [ ] get, set, delete
- [x] call
- [x] delitem, contains
- [ ] missing, reversed
- [x] iter
- [ ] getslice, setslice, delslice
- [x] add/sub/mul/floordiv/mod/...
- [x] radd/rsub/rmul/...
- [x] iadd/isub/imul/...
- [ ] neg, pos, abs, invert, complex, int, long, float
- [ ] coerce
- [ ] enter, exit

**Comment by corona10** [comment]
i fix '__eq__ overload not working #253' on pull request #380 (i think i need to sperate pull request but i don't know how to do.. sorry)

**Comment by dorafmon** [comment]
These two functions in ``classobject.cpp`` share the exact same structure:
```C++
Box* instanceEq(Box* _inst, Box* other) {
    RELEASE_ASSERT(_inst->cls == instance_cls, "");
    BoxedInstance* inst = static_cast<BoxedInstance*>(_inst);

    Box* func = _instanceGetattribute(inst, boxStrConstant("__eq__"), false);
    if (!func)
        return NotImplemented;
    return runtimeCall(func, ArgPassSpec(1), other, NULL, NULL, NULL, NULL);
}

Box* instanceNe(Box* _inst, Box* other) {
    RELEASE_ASSERT(_inst->cls == instance_cls, "");
    BoxedInstance* inst = static_cast<BoxedInstance*>(_inst);

    Box* func = _instanceGetattribute(inst, boxStrConstant("__ne__"), false);
    if (!func)
        return NotImplemented;
    return runtimeCall(func, ArgPassSpec(1), other, NULL, NULL, NULL, NULL);
}
```
I am just wondering does all the functions mentioned above should be treated as these two? Calling the object's implementation and raise an exception if there is no implementation. If so shouldn't we write a single function to unify this behaviour?

**Comment by Daetalus** [comment]
Does this issue need to be update? Some of the attribute seems already implemented.
