### ISSUE TITLE
consider enabling gitter.im for real time chat - https://gitter.im/

### ISSUE THREAD

**Issue by dagar** [dropbox/pyston#255]
@kmod - Enabling https://gitter.im/ would allow easy real time chat. It's like irc with github integration, but it's web based, persistent, and auto adds a join badge to the README.md (eg https://github.com/PX4/Firmware/blob/master/README.md).

**Comment by dorafmon** [comment]
:+1:

**Comment by kmod** [comment]
Come one come all: https://gitter.im/dropbox/pyston
