### ISSUE TITLE
Improve generator switching speed

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#261]
We use swapcontext() to switch between generators, which works but is overkill for what we need.  The worst is that it saves the signal mask, which involves a syscall, when we want all of our threads to have the same signal mask.  It also saves the x87 floating point state (I don't think we use that?) and caller-save registers which are guaranteed to be already saved by the calling convention.

As for options, we could use setjmp/longjmp, though those don't help with the initial setup of the new context.  We could also provide our own optimized swapcontext().

Here's an example:
http://www.1024cores.net/home/lock-free-algorithms/tricks/fibers

We have a simple microbenchmark to measure this: microbenchmarks/generator_switching.py.

**Comment by undingen** [comment]
We may also want to try and benchmark boost context:
http://www.boost.org/doc/libs/1_57_0/libs/context/doc/html/context/performance.html
