### ISSUE TITLE
select_test fails

### ISSUE THREAD

**Issue by tjhance** [dropbox/pyston#272]
EPOLLET is wrong.

```
tjhance@dbdev:~/pyston $ python ./test/tests/select_test.py
EPOLLERR 8
EPOLLET -2147483648
EPOLLHUP 16
EPOLLIN 1
EPOLLMSG 1024
EPOLLONESHOT 1073741824
EPOLLOUT 4
EPOLLPRI 2
EPOLLRDBAND 128
EPOLLRDNORM 64
EPOLLWRBAND 512
EPOLLWRNORM 256
POLLERR 8
POLLHUP 16
POLLIN 1
POLLMSG 1024
POLLNVAL 32
POLLOUT 4
POLLPRI 2
POLLRDBAND 128
POLLRDNORM 64
POLLWRBAND 512
POLLWRNORM 256

tjhance@dbdev:~/pyston $ ./pyston_dbg ./test/tests/select_test.py
EPOLLERR 8
EPOLLET 2147483648
EPOLLHUP 16
EPOLLIN 1
EPOLLMSG 1024
EPOLLONESHOT 1073741824
EPOLLOUT 4
EPOLLPRI 2
EPOLLRDBAND 128
EPOLLRDNORM 64
EPOLLWRBAND 512
EPOLLWRNORM 256
POLLERR 8
POLLHUP 16
POLLIN 1
POLLMSG 1024
POLLNVAL 32
POLLOUT 4
POLLPRI 2
POLLRDBAND 128
POLLRDNORM 64
POLLWRBAND 512
POLLWRNORM 256
```

**Comment by kmod** [comment]
Oh interesting -- I think you must be running a 32-bit build of CPython?  This feels like a ~bug in CPython if they treat EPOLLET as signed and then let it wrap around like that, so I'm inclined to say that our behavior is correct; I'll update the test.

It also brings up an interesting point that we target a specific CPython (64-bit 2.7.7) whereas we test against whatever system python the machine has installed.  Hopefully this doesn't become too much of a nuisance and we can just make the tests not rely on bitness or micro-version details.

**Comment by kmod** [comment]
I think that referenced commit should fix it -- can you try it again on your system?

**Comment by kmod** [comment]
Ok did a little bit of digging, and this seems to just be a bug in our build of Python.  We do a pretty good job of preserving the build steps to rebuild all of our packages, but when I ran those for our build of Python, I got the correct value for EPOLLET.  I reported the issue to the infra team, and modified the test to just work around it.
