### ISSUE TITLE
Support del-unpacking

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#294]
I didn't even know this was a thing, but apparently this is perfectly valid:
```python
del [a, (b,) ([c.a], d[1])]
```
and it deletes a, b, c.a, and d[1].

(See [del_multi.py](https://github.com/dropbox/pyston/blob/master/test/tests/del_multi.py))

This should be a pretty simple change in the AST-to-CFG conversion to flatten these (see `cfg.cpp::visit_delete()`).

**Comment by vinzenz** [comment]
Currently still failing:

>> del [a, (b,) ([c.a], d[1])]
../../src/core/cfg.cpp:1846: virtual bool pyston::CFGVisitor::visit_delete(pyston::AST_Delete *): Assertion `0' failed: Unsupported del target: 9


=> It most likely should fail on the fact that a tuple is not callable even before this assert pops up

**Comment by kmod** [comment]
Oh, I think that was a typo in my example.

I think this is fixed now though; closing.
