### ISSUE TITLE
CMake build doesn't track header dependencies in runtime/inline?

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#339]
@dagar 
I think that our custom commands for handling the runtime/inline directory don't know about header file dependencies, so when I updated a header file they didn't rebuild and then the link failed.  Would you mind taking a look?

**Comment by dagar** [comment]
Creating the header dependency file is easy, but getting that into cmake so it can be used by the generated makefiles, ninja, etc might be hard. I'll look into it.

**Comment by dagar** [comment]
I'll admit this sucks, but as a (hopefully) temporary solution what do you think about just using all the headers as dependencies for src/runtime/inline/*.cpp? I can also get ccache working for those files.

**Comment by kmod** [comment]
Oh hmm I assumed that ccachhe had some way of handling this because it looks like it gets the header dependencies for our "normal" compilation steps.

But I think depending on all the header files is fine for now :)

**Comment by dagar** [comment]
Ccache isn't being used for runtime/inline because the compiler is set manually, so if those files are going to rebuild every time any header is touched I'll make sure they're cached.
