### ISSUE TITLE
Needs notice about new library

### ISSUE THREAD

**Issue by corona10** [dropbox/pyston#383]
after new merged about supporting sqlite3
new library('sqlite3') needed for compiling (libsqlite3-dev package)

I thinks that somebody notice about this kinds of issue.

**Comment by corona10** [comment]
oh i found install.md that notice about that

**Comment by kmod** [comment]
Yeah, we need to have a better system for notifying people with existing dev setups of any changes that they need to make.  Ideally we make all the updates automatic, but sometimes (like this one) it's tough.
