### ISSUE TITLE
close my pull request 

### ISSUE THREAD

**Issue by corona10** [dropbox/pyston#391]
omg... every my code which i push to my repository changed my pull request #337  so i closed it..
lot's of conflict in using git , i need to fix it (such as re-fork main repository.. and make branch..)
so i closed it
can @kmod  remove my pull request log #337?
i need to newly start it haha

**Comment by undingen** [comment]
Ok I think the easiest solution for you would be:
copy the current content (with your changes) of the ```src/gc/collector.cpp``` file to some tmp directory.
then run: ```git checkout -b smallvector upstream/master```
You will then have a local branch with the name ```smallvector``` witch is tracking the pyston master branch.
Copy over you changed file.
Add, commit and push the change to the repository. 
The next time you want to modify something you will create a new branch again (with a different name)

**Comment by corona10** [comment]
thank you it's hard than just using as college project.
