### ISSUE TITLE
Opened files not being closed.

### ISSUE THREAD

**Issue by BurningPixel** [dropbox/pyston#396]
Hopefully I'm not misrepresenting this, but it seems that in some python code files opened via the open() method are not being closed.

For example in pyston/tools/perf_diff.py

``` python
def tally(fn):
    counts = {}

    for l in open(fn):
        samples = int(l.split()[3])
        func = l.split()[-1]
        counts[func] = samples

    return counts
```

This is my first time opening an issue on a large open source project so sorry if did something wrong.

**Comment by vinzenz** [comment]
This is a mistake on your part, you have to close it manually or have to use the with statement.

```with open(fn) as f:
    for l in f:
        ... and so on```

**Comment by kmod** [comment]
Yeah true, it's sloppy on our part, though when not writing to the file, the main issue it could cause is a potential exhaustion of file descriptors (though it looks like we also do this when writing too...).  Personally I find it to be quite a nuisance to write out the full with statement and I wish Python had C++-style RAII.

But anyway, yeah it's not great, and if anyone wanted to help fix it we'd definitely take that contribution :)
