### ISSUE TITLE
cmake's way of building/using libunwind is different from makefile?

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#402]
@dagar sorry for the vague description but I'm not sure what's going on here.  We just added an optimization for some of our stack unwinding (https://github.com/dropbox/pyston/commit/239b08c3dc59db1330bcccd65e41d7adf8161025) and it seems to be a great help when built from the Makefile, but to have no effect when built using cmake.

It's a little tricky to measure since we use different libunwind revisions for cmake and the Makefile build; these are for the Makefile rev:
- Makefile, without change: 5.6s
- Makefile, with change: 2.8s
- CMake, without change: 8.3s
- CMake, with change: 5.1s

And for the CMake rev:
- Makefile, with or without change: 5.9s
- CMake, with or without change: 8.5s

So it looks like libunwind changed something that erased the benefit of this change, but still in all configurations the CMake build is slower than the Makefile build :(

To test, you can do:
```
cd libunwind; git checkout 65ac867416; cd ..
git checkout 5c42a2abd45f # without the change
git checkout 62f7f2f4bd209 microbenchmarks/exceptions_ubench.py # an updated version of the microbenchmark
make run_release_exceptions_ubench USE_CMAKE=0
make run_release_exceptions_ubench USE_CMAKE=1

git checkout 239b08c3dc59 # with the change
git checkout 62f7f2f4bd209 microbenchmarks/exceptions_ubench.py
make run_release_exceptions_ubench USE_CMAKE=0
make run_release_exceptions_ubench USE_CMAKE=1
```

I looked at the libunwind build log from cmake, and it looks like it's not passing any optimization arguments.  I added `-O2 -DNDEBUG` and this improved the time to 6.5s, which is still not quite as good as the Makefile time (5.9s) but I guess more in the ballpark and there could be something else that's the issue.  Would you mind taking a look?

**Comment by dagar** [comment]
CMake builds libunwind with -O0 -g in CMAKE_BUILD_TYPE=Debug. In release mode it ends up passing CFLAGS='' to libunwind configure, which apparently wipes out -O2. This is fixed in PR #405

I'm still compiling LLVM with the Makefile so I'll see if anything else is different.

**Comment by dagar** [comment]
PR #405 resolves most of it, but the cmake build is still 10-20% slower. I'll keep looking.

**Comment by dagar** [comment]
It's the libunwind version. Using the same libunwind commit as the Makefile with CMake is the same speed.

master
Makefile 2.686
CMake 7.097

cmake-libunwind
Makefile 2.655
CMake 4.942

cmake-libunwind + libunwind 65ac867416 (Makefile version)
Makefile 2.665
CMake 2.644

I'll try bisecting libunwind

**Comment by dagar** [comment]
The offending libunwind commit disables per thread caching. I'll revert the libunwind submodule in PR #405 for now.

5b37b3cff142f82c47dbdc41dc11f2ef122294ac is the first bad commit
commit 5b37b3cff142f82c47dbdc41dc11f2ef122294ac
Author: Simon Atanasyan <simon@atanasyan.com>
Date:   Thu Oct 23 11:35:00 2014 -0700

    Fix intermittent failures of Lrs-race test case

**Comment by kmod** [comment]
Ok cool, they seem even now :)  I pulled the change and then ran ninja, but it looks like it didn't update the libunwind submodule.  I ran `git submodule update` and got the new code, but then ninja didn't think that libunwind needed to be rebuilt, so I had to rm -rf the directory.

**Comment by dagar** [comment]
CMake only handles git submodule update if the .gitmodules file changes. The actual commit to keep each submodule at is in the object database (not easily accessible to cmake). We could have the gitsubmodules target always out of date and run every time ninja is invoked?

**Comment by kmod** [comment]
Drat, ok let's just leave it the way it is and curse submodules for working the way they do.  (Running it every time seems like it would make it hard to test out different revisions?)

Well, I did have an issue in a personal branch where I had retargeted a submodule but forgot to push that revision of the submodule, which got things very confused.  So I guess there's not necessarily any good way to solve this, but I still feel like submodules didn't pick the best option out of the bunch.

**Comment by dagar** [comment]
Ninja running 'git submodule update' every time would force it to the
tracking commit stored in Pyston. Although, uncommitted changes in the
submodule are kept. It's also possible to set update in .gitmodules to do
whatever you want (merge, rebase, nothing, or any command).

I still think submodules are the least terrible method for tracking source
dependencies. At least everyone (and the build) starts with identical
source and can sync up with one command. Let me know if you'd like to try
something else.

On Tue, Mar 24, 2015 at 3:20 PM, Kevin Modzelewski <notifications@github.com
