### ISSUE TITLE
What does "Expected failure (got code -6, should be 1)" mean?

### ISSUE THREAD

**Issue by arbipher** [dropbox/pyston#431]
For example when I run "make check_assign_literal", it says
"Expected failure (got code -6, should be 1)"

The content of test/assign_literal.py is
> \# expected: fail
> 2 = 2

I know it's wrong since we can not assign to literal. My question is where does "-6" and "1" come from?

**Comment by kmod** [comment]
Hmm yeah it's not clear, but it's talking about the exit codes of Pyston vs CPython.  1 is the exception code that CPython uses when program exits by throwing an exception, which in this case is a SyntaxError.  -6 is -SIGABRT, which means that we called abort(), which is probably from a failed assert() ie not handling that SyntaxrError gracefully.  So it just means that we were expected to fail gracefully but we crashed instead.  For exitcode (crashing) issues, it's usually easier to debug if you do `make run_assign_literal` and `make pyrun_assign_literal`.
