### ISSUE TITLE
Instructions are broken for ubuntu 14.04

### ISSUE THREAD

**Issue by ekarlso** [dropbox/pyston#439]
ubuntu@pyston:~/pyston-build$ CC='clang' CXX='clang++' cmake -GNinja ~/pyston
CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineCCompiler.cmake:56 (message):
  Could not find compiler set in environment variable CC:

  clang.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file: /home/ubuntu/pyston-build/CMakeFiles/2.8.12.2/CMakeCCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER
CMake Error: Could not find cmake module file: /home/ubuntu/pyston-build/CMakeFiles/2.8.12.2/CMakeCXXCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_ASM_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_ASM_COMPILER
CMake Error: Could not find cmake module file: /home/ubuntu/pyston-build/CMakeFiles/2.8.12.2/CMakeASMCompiler.cmake
-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/pyston-build/CMakeFiles/CMakeOutput.log".

**Comment by arbipher** [comment]
It seems you are installing pyston using CMake
The error message "Could not find compiler set in environment variable CC" tells CC is missing.
Since CC='clang' in command, you might miss clang.

Instructions for 14.04 is at the end of [INSTALLING.md](https://github.com/dropbox/pyston/blob/master/docs/INSTALLING.md)

The first line is

> sudo apt-get install -yq git cmake ninja-build ccache libncurses5-dev liblzma-dev libreadline-dev libgmp3-dev autoconf libtool python-dev texlive-extra-utils clang-3.5 libssl-dev libsqlite3-dev

Noting there is a clang-3.5 in it.

Maybe you forgot to install them.

**Comment by dagar** [comment]
I think the actual binaries are named with the version now. I newer GCC would also work.
CC='clang-3.5' CXX='clang++-3.5' cmake -GNinja ~/pyston

I'll update the documentation.

**Comment by kmod** [comment]
This seems like a bug in the clang packages?  They seem to claim to provide /usr/bin/clang (seen in `command-not-found` or `apt-file search`) but don't actually install it.  Our makefile-to-cmake shim also assumes that `clang` is available; how about we have the instructions just manually set up the symlinks? (I think this is only necessary for the 3.5 package.)

**Comment by dagar** [comment]
Yes, it's a bug in the trust clang-3.5 package.
https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-snapshot/+bug/1420570

**Comment by dagar** [comment]
We could just change the 14.04 instructions to install clang 3.4, which the 'clang' virtual package installs. Then it's also the same version for the Ubuntu 12.04 and 14.04 instructions.
