### ISSUE TITLE
cmake build error

### ISSUE THREAD

**Issue by tjhance** [dropbox/pyston#470]
When building with cmake I get

```
CMake Error at CMakeLists.txt:120 (add_subdirectory):
  add_subdirectory given source "lz4/cmake_unofficial" which is not an
  existing directory.


CMake Error at CMakeLists.txt:121 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "lz4".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.

```

I have followed the instructions in the `doc/INSTALLING.md` for lz4. The directory `~/pyston_deps/lz4/cmake_unofficial` exists, so I have no idea what's going on.

**Comment by undingen** [comment]
I think for the CMake build
```
git submodule init
git submodule update
```
should be enough you should not need the pyston_deps/lz4...
Weird that it does not work.

**Comment by tjhance** [comment]
Ah so that did seem to be the problem. I hadn't realized that there were more submodules added, so I needed to `init` again. Thanks!

Ah, git-submodule, my old enemy...
