### ISSUE TITLE
getting started with cmake

### ISSUE THREAD

**Issue by tjhance** [dropbox/pyston#472]
I am just now attempting to get onto the cmake build system. (Late to the party, I know). I started completely from scratch.

Following the instructions, I ran

```
git clone --recursive https://github.com/dropbox/pyston.git ~/pyston

git clone git://github.com/llvm-mirror/llvm.git ~/pyston_deps/llvm-trunk
git clone git://github.com/llvm-mirror/clang.git ~/pyston_deps/llvm-trunk/tools/clang
cd ~/pyston
make llvm_up
make
make check
```

The last step failed with
```
ninja: Entering directory `/home/tjhance/pyston-build-release'
ninja: error: loading 'build.ninja': No such file or directory
make[1]: *** [check_format] Error 1
make[1]: Leaving directory `/home/tjhance/pyston'
make: *** [check] Error 2
```

I decided to try
```
make pyston_release
```

`make check` was then able to get a bit farther, but it still failed with
```
ccache: FATAL: /home/tjhance/pyston_deps/llvm-trunk-build/Release/bin/clang: execv returned (No such file or directory)
make[1]: *** [test/test_extension/basic_test.o] Error 1
make[1]: Leaving directory `/home/tjhance/pyston'
make: *** [check] Error 2
```
Indeed, there is no `/home/tjhance/pyston_deps/llvm-trunk-build/Release/` directory.

I am not sure why I am missing this. I did run `make llvm_up`, and there are no other llvm/clang instructions under the cmake setup instructions.

**Comment by tjhance** [comment]
Even though the cmake instructions didn't specify, I did try building llvm using the old commands (uncertain as I was that it would be the correct thing to do).

```
make llvm_configure
make llvm
```

But the first command failed with
```
checking tool compatibility... configure: error: g++|clang++|icc required but not found
make[1]: *** [/home/tjhance/pyston_deps/llvm-trunk-build/Makefile.config] Error 1
```

This is strange because I do have g++ _and_ clang++ on my system, and I do not know what I would need to do for it to find them.

**Comment by tjhance** [comment]
I just want to add that (in spite of these difficulties) it's awesome that I was able to get through the `make` step and have a working `pyston_dbg` binary so easily. This is much nicer than the laundry list of things to manually install that comprised our previous build system. Thanks @dagar !

**Comment by kmod** [comment]
It looks like we don't have the shim set up to compile the test extension modules using cmake, or support in CMake for building those.  Can you try running `make ext_pyston_selfhost && make check`?  That will build the extension modules using the setup.py file instead of hardcoding the build rules in the makefile.  If this works we should probably default to selfhosting the extension modules when in cmake mode.

**Comment by tjhance** [comment]
That still doesn't work. `make ext_pyston_selfhost` runs

```
gcc -pthread -fno-strict-aliasing -g -O3 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/tjhance/pyston/test/test_extension/../../from_cpython/Include -c -Werror=implicit-function-declaration basic_test.c -o build/temp.linux2-2.7/basic_test.o
```

On the other hand, `make check` attempts to build with

```
CCACHE_CPP2=yes ccache /home/tjhance/pyston_deps/llvm-trunk-build/Release/bin/clang -pthread -g -Werror -Wreturn-type -Wall -Wno-sign-compare -Wno-unused -Isrc -Ifrom_cpython/Include -fno-omit-frame-pointer -Wextra -Wno-sign-compare -Wno-unused-parameter  -fPIC -Wimplicit -O2 -Ifrom_cpython/Include -Wno-missing-field-initializers -Wno-tautological-compare -Wno-type-limits -Wno-strict-aliasing -enable-tbaa -ferror-limit=10 -Qunused-arguments -fcolor-diagnostics -c test/test_extension/basic_test.c -o test/test_extension/basic_test.o
```

The destination directories are different: `test/test_extension/basic_test.o` vs `build/temp.linux2-2.7/basic_test.o`

**Comment by kmod** [comment]
Hmm that should be taken care of by the selfhoster manually symlinking the .so's into the right spot... what ends up actually failing?

Also how do you feel about moving the conversation to gitter?

**Comment by tjhance** [comment]
So while I did get everything working, the output of all commands does start with

```
make: /home/tjhance/pyston_deps/llvm-trunk-build/Release+Asserts/bin/llvm-config: Command not found
make: /home/tjhance/pyston_deps/llvm-trunk-build/Release+Asserts/bin/llvm-config: Command not found
make: /home/tjhance/pyston_deps/llvm-trunk-build/Debug+Asserts/bin/llvm-config: Command not found
```

Even though the command still runs, this is a bit distracting and makes me feel like something is still wrong with my setup.

**Comment by kmod** [comment]
I checked in a change a little while ago that silenced those errors; I think we were able to work through everything so I'm going to go ahead and close this.
