### ISSUE TITLE
Parser need to improve for parse float?

### ISSUE THREAD

**Issue by Daetalus** [dropbox/pyston#722]
Pyston seems treat something like `0e7` as `SyntaxError`. Maybe the parser needs some improvements?

BTW, something like `0.0 = -0.1` should report `SyntaxError`, not abort directly.

**Comment by tjhance** [comment]
Syntax errors should be filed as issues at https://github.com/vinzenz/libpypa.

I fixed the `0e7` in libpypa a while back; it looks like pyston just needs to update to libpypa/master.

I'll file an issue with libpypa for the assignment problem.

**Comment by tjhance** [comment]
filed: https://github.com/vinzenz/libpypa/issues/39

**Comment by Daetalus** [comment]
Thanks @tjhance ! Another questions, it seems pypa treat the negative sign before a literal float number as part of the number , such as `-0.1`. And treat the negative sign before float variable as an unary operator. But for positive sign it always treat is as unary operator(Although the `float.__pos__` not implemented in Pyston, yet).

Is that intended?

**Comment by tjhance** [comment]
The easiest way to check something like that is by playing around with the `ast` module in cpython. For example,

```
>>> import ast
>>> ast.dump(ast.parse("+5"))
'Module(body=[Expr(value=UnaryOp(op=UAdd(), operand=Num(n=5)))])'
>>> ast.dump(ast.parse("-5"))
'Module(body=[Expr(value=Num(n=-5))])'
```

Interestingly, it looks like it _is_ intentional that the '-' is part of the literal, but the '+' is an operator; that's what the CPython grammar does, anyway.
