### ISSUE TITLE
-0.0 could not convert to str correctly(maybe the `floatFormat` problem?`)

### ISSUE THREAD

**Issue by Daetalus** [dropbox/pyston#724]
`str(-0.0)` and `print(-0.0)` could not get constant and correct output. For example(Pyston 0.3):

```
print str(-0.0)
nums = [0, 0.0, -0.0]

print str(-0.0)
for num in nums:
    print num
```
will output:
```
-0.0
-0.0
0
-0.0
-0.0
```
But if comment the first line:
```
#print str(-0.0)
nums = [0, 0.0, -0.0]

print str(-0.0)
for num in nums:
    print num
```
the output will change to:
```
0.0
0
0.0
0.0
```

So in most situations, `print -0.0` will output `0.0`.

**Comment by kmod** [comment]
oh wow, good find.  I thought this might have something to do with our float-caching code, but it looks like `-(0.0)` has the same result.  I'll take a look into this.

**Comment by kmod** [comment]
Nevermind, looks like it was due to the float-caching stuff.  I think #725 should fix this.
