### ISSUE TITLE
Can I translate the bitcode created by pyston to IR?

### ISSUE THREAD

**Issue by lanyuesl** [dropbox/pyston#841]
When I run 
./pyston xxx.py
I get a file called xxx.pyc, which I think is the bitcode of xxx.py. And when I run 
llvm-dis -o xxx.ll xxx.pyc
I get an error Invalid bitcode signature
And now I want to see the IR(Intermediate Representation) of the source code xxx.py.
How?

**Comment by undingen** [comment]
The ```.pyc``` file stores the AST nodes the parser generated for the file. It doesn't store any LLVM IR currently. If you would like to see the generated LLVM IR you have to run pyston with higher verbosity. We also only use the LLVM tier for very hot functions/loops. So if you would like to see the generated llvm IR for every functions you have to specify "-n".
So something like this should work: ```./pyston_dbg -S -n -v -v t.py```.
But I'm curious why do you want to see the LLVM IR? The IR we emit is very pyston specific and the flag is only useful for debugging purposes. At least I can't think of anything else.
We also have a pyston gitter channel. Where it's probably easier to discuss followup questions :-)

**Comment by lanyuesl** [comment]
Thank you undingen.
We are working on to generate Call-gragh for different language, including C/C++, Python, Java and so on. However, because of function pointers, it is impossible to generate that on source code. It is our plan to generate that on LLVM IR . So we are trying to translate different language to the LLVM IR.
We find that it is easy to generate python AST by Python AST node. And we think your work on ast-interpreter will be helpful to us. So I am here to analyze pyston:)
