### ISSUE TITLE
Support the "termios" module

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#898]
Not super high priority, but I've had to stub this out a couple times.  Having only taken a quick glance, I think this might be pretty straightforward -- hopefully should just be a matter of adding termios.c to our build system.

CPython doesn't have any test for the termios module, but it looks like the test_ioctl.py (not copied into Pyston yet) test will use it if it is available.  If we can get that to work that's probably a good enough test for now.

@Daetalus interested?

**Comment by Daetalus** [comment]
@kmod Working on it. Thanks!

**Comment by kmod** [comment]
oh hmm yes it looks like we have it, not sure how I got this confused.
