### ISSUE TITLE
Support the "ast" module

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#902]
I think this boils down to just implementing the "_ast" module which has the actual Python types.  We have a simple module (src/runtime/builtin_modules/ast.cpp) that declares the different types, but they're currently empty.

I think any individual type is pretty straightforward, but there are 90 of them.  CPython auto-generates their module (Python/Python-ast.c) from their grammar file.  We could try to modify their grammar generator, or modify the output, or just continue to implement the module from scratch.

**Comment by aisk** [comment]
I'll try this :smile_cat:

**Comment by corona10** [comment]
i done by modifying some files and add 

```	
new file:   from_cpython/Include/Python-ast.h
new file:   from_cpython/Include/asdl.h
new file:   from_cpython/Python/Python-ast.c
new file:   from_cpython/Python/asdl.c
new file:   from_cpython/Python/pyarena.c

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   from_cpython/CMakeLists.txt
```
but i don't know what to next

**Comment by Daetalus** [comment]
My proposal is write some types manually first. Summarize and find the pattern, them modify CPython grammar generator, or write the module from scratch. Just some thoughts, not verify it.

**Comment by corona10** [comment]
@Daetalus  so it means code generator should makes src/runtime/builtin_modules/ast.cpp??

**Comment by Daetalus** [comment]
Just my proposal, wait for @kmod to give some concrete suggestions

**Comment by kmod** [comment]
I agree with daetalus, I don't think we should jump straight to using their generator.  I think there are a couple ways we could attack this, but the one I would suggest is:
- copy in Python-ast.c (and just that file)
- try to convert it from using CPython's AST structs (Python-ast.h) to our AST structs (src/core/ast.h)
- see what needs to be changed; if it's a small amount I would just make the changes in the generated file.  if it's a lot, then maybe take a look at the generator to see if modifying that would be easier.
