### ISSUE TITLE
Pass CPython's "test_set"

### ISSUE THREAD

**Issue by kmod** [dropbox/pyston#914]
ie `make run_test_set`.  Looks like there are quite a few failures there, which is concerning.

**Comment by kmod** [comment]
I got some of them in #915, but there are still a bunch more.  I'm not sure what they all are, but they seem mostly pretty straightforward, such as "most set functions can take sets as keys and will convert them to frozensets".  Another example is that we seem to have an issue pickling sets.

**Comment by Daetalus** [comment]
Working on it.

**Comment by kmod** [comment]
Cool!  The test is pretty big, so it might help to only run parts of it at a time (there's a list at the bottom of the test sets it will run).  We probably can't get the whole test working right away, so as we fix things we should just copy those tests into our own set.py test.
