### ISSUE TITLE
Can we switch to CPython "long" implementation from now?

### ISSUE THREAD

**Issue by Daetalus** [dropbox/pyston#968]
I try to fixing `test_long_future`, `test_long`, `test_fractions`, `test_csv`. These tests are related to long implementaion. Most of the problems could solved by introduce `mpfr` and with some other improvements. But after finish today's work. I realized that there has high probability that these works may make no sense at the end.

In order to support cross platform and 3rd party modules. We may need to swtich to CPython `long` implementation eventually. eg. `math` module use `PY_SIZE` to check a long object whether is negative or zero, we don't support it now. Beside patch the current long implementation. We can go further.

And even use `mpfr` as a bridge, I still could not solve some corner case in long true div. I read the source code and documentation of `MPFR`. The value is truncated inside `mpfr`(with some round type, but none of them could address all corner case). 

I know the current implementation is faster, and maybe switch to CPython implementaion not has high priority. But I think we can start it from now. I have some improvements about the current `long` implementation. But I highly doubt it will become meaningless in foreseeable future...

**Comment by kmod** [comment]
Oh hmm that's unfortunate.  I think GMP is about twice as fast as CPython's long implementation, so it'd be nice to keep using it.  But this isn't the first time we've run into long compatibility issues, especially with the C API.

@undingen what do you think?  I could see this going either way.

**Comment by undingen** [comment]
I thought using GMP was a good idea but I don't have much knowledge in this area.
Maybe we should just keep the current long support and decide if we should switch if someone has a codebase which requires additional long support.

**Comment by corona10** [comment]
i think #256 issue also related with this issue.
